In [1]:
# Imports the Pandas library and stores the dataset into a dataframe
import pandas as pd
poll_url = 'http://projects.fivethirtyeight.com/general-model/president_general_polls_2016.csv'
polls = pd.read_csv(poll_url)

In [2]:
# Displays the first 5 rows of the data
polls.head()

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,ABC News/Washington Post,A+,...,45.20163,41.72430,4.626221,NaN,NaN,https://www.washingtonpost.com/news/the-fix/wp...,48630,76192,11/7/16,09:35:33 8 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/1/2016,11/7/2016,Google Consumer Surveys,B,...,43.34557,41.21439,5.175792,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48847,76443,11/7/16,09:35:33 8 Nov 2016
2,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/2/2016,11/6/2016,Ipsos,A-,...,42.02638,38.81620,6.844734,NaN,NaN,http://projects.fivethirtyeight.com/polls/2016...,48922,76636,11/8/16,09:35:33 8 Nov 2016
3,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/4/2016,11/7/2016,YouGov,B,...,45.65676,40.92004,6.069454,NaN,NaN,https://d25d2506sfb94s.cloudfront.net/cumulus_...,48687,76262,11/7/16,09:35:33 8 Nov 2016
4,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,Gravis Marketing,B-,...,46.84089,42.33184,3.726098,NaN,NaN,http://www.gravispolls.com/2016/11/final-natio...,48848,76444,11/7/16,09:35:33 8 Nov 2016

In [6]:
# Sorts the dataframe according to column name 'state' and displays first 2 rows
polls.sort_values('state', inplace=True)
polls.head(2)

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
12475,2016,President,polls-only,Clinton vs. Trump vs. Johnson,11/8/16,Alabama,10/21/2016,11/2/2016,Ipsos,A-,...,40.48323,53.28125,NaN,NaN,NaN,http://www.reuters.com/statesofthenation/,48213,75514,11/3/16,09:14:14 8 Nov 2016
4610,2016,President,now-cast,Clinton vs. Trump vs. Johnson,11/8/16,Alabama,11/1/2016,11/7/2016,Google Consumer Surveys,B,...,25.54403,66.17603,3.75508,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48794,76383,11/7/16,09:24:53 8 Nov 2016

## Clean the data

In [7]:
polls.sort_values('state', ascending=False).head

<bound method NDFrame.head of        cycle     branch        type                        matchup  \
5595    2016  President    now-cast  Clinton vs. Trump vs. Johnson
9368    2016  President  polls-only  Clinton vs. Trump vs. Johnson
11204   2016  President  polls-only  Clinton vs. Trump vs. Johnson
1336    2016  President  polls-plus  Clinton vs. Trump vs. Johnson
10098   2016  President  polls-only  Clinton vs. Trump vs. Johnson
...      ...        ...         ...                            ...
3318    2016  President  polls-plus  Clinton vs. Trump vs. Johnson
9971    2016  President  polls-only  Clinton vs. Trump vs. Johnson
3304    2016  President  polls-plus  Clinton vs. Trump vs. Johnson
3165    2016  President  polls-plus  Clinton vs. Trump vs. Johnson
12475   2016  President  polls-only  Clinton vs. Trump vs. Johnson

      forecastdate    state   startdate     enddate                 pollster  \
5595       11/8/16  Wyoming  10/24/2016  10/30/2016             SurveyMonkey
9368       11/8/16  Wyoming  10/25/2016  10/31/2016  Google Consumer Surveys
11204      11/8/16  Wyoming   8/24/2016   8/30/2016  Google Consumer Surveys
1336       11/8/16  Wyoming  10/25/2016  10/31/2016             SurveyMonkey
10098      11/8/16  Wyoming  10/10/2016  10/14/2016  Google Consumer Surveys
...            ...      ...         ...         ...                      ...
3318       11/8/16  Alabama   8/17/2016   8/23/2016  Google Consumer Surveys
9971       11/8/16  Alabama   9/30/2016  10/20/2016                    Ipsos
3304       11/8/16  Alabama   7/29/2016   8/18/2016                    Ipsos
3165       11/8/16  Alabama   8/24/2016   8/30/2016  Google Consumer Surveys
12475      11/8/16  Alabama  10/21/2016   11/2/2016                    Ipsos

      grade  ...  adjpoll_clinton adjpoll_trump  adjpoll_johnson  \
5595     C-  ...         21.66060      62.70650         4.911339
9368      B  ...         32.16531      63.84652         2.557269
11204     B  ...         29.19806      52.00241         5.173976
1336     C-  ...         20.71510      62.43554         7.034882
10098     B  ...         22.26467      60.78201         9.642412
...     ...  ...              ...           ...              ...
3318      B  ...         25.24864      65.91230         1.211924
9971     A-  ...         37.21149      53.39428              NaN
3304     A-  ...         35.64400      56.35091              NaN
3165      B  ...         24.57778      64.97036         3.560686
12475    A-  ...         40.48323      53.28125              NaN

       adjpoll_mcmullin  multiversions  \
5595                NaN            NaN
9368                NaN            NaN
11204               NaN            NaN
1336                NaN            NaN
10098               NaN            NaN
...                 ...            ...
3318                NaN            NaN
9971                NaN            NaN
3304                NaN            NaN
3165                NaN            NaN
12475               NaN            NaN

                                                     url  poll_id  \
5595   https://www.surveymonkey.com/elections/map?pol...    47844
9368   https://datastudio.google.com/u/0/#/org//repor...    47992
11204  https://drive.google.com/drive/u/0/folders/0B2...    45540
1336   https://www.surveymonkey.com/elections/map?pol...    47933
10098  https://datastudio.google.com/u/0/#/org//repor...    47006
...                                                  ...      ...
3318   https://drive.google.com/drive/u/0/folders/0B2...    45542
9971           http://www.reuters.com/statesofthenation/    47185
3304            http://www.reuters.com/statesofthenation    44940
3165   https://drive.google.com/drive/u/0/folders/0B2...    45491
12475          http://www.reuters.com/statesofthenation/    48213

       question_id  createddate             timestamp
5595         74867     10/31/16  09:24:53  8 Nov 2016
9368         75051      11/1/16  09:14:14  8 Nov 2016
11204        70925       9/9/16  09:14:14  8 Nov 2016
1336         74989      11/1/16  09:35:33  8 Nov 2016
10098        73495     10/17/16  09:14:14  8 Nov 2016
...            ...          ...                   ...
3318         70927       9/9/16  09:35:33  8 Nov 2016
9971         73862     10/22/16  09:14:14  8 Nov 2016
3304         68973      8/24/16  09:35:33  8 Nov 2016
3165         70809       9/9/16  09:35:33  8 Nov 2016
12475        75514      11/3/16  09:14:14  8 Nov 2016

[12624 rows x 27 columns]>

### Keep only the rows with "now-cast" in the type column

In [8]:
polls = polls.query('type=="now-cast"')
polls.head()

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
4610,2016,President,now-cast,Clinton vs. Trump vs. Johnson,11/8/16,Alabama,11/1/2016,11/7/2016,Google Consumer Surveys,B,...,25.54403,66.17603,3.755080,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48794,76383,11/7/16,09:24:53 8 Nov 2016
5997,2016,President,now-cast,Clinton vs. Trump vs. Johnson,11/8/16,Alabama,10/27/2016,11/2/2016,SurveyMonkey,C-,...,33.63222,52.90133,2.269698,NaN,NaN,https://www.surveymonkey.com/elections/map?pol...,48129,75398,11/3/16,09:24:53 8 Nov 2016
7530,2016,President,now-cast,Clinton vs. Trump vs. Johnson,11/8/16,Alabama,8/17/2016,8/23/2016,Google Consumer Surveys,B,...,25.27439,65.91888,1.217370,NaN,NaN,https://drive.google.com/drive/u/0/folders/0B2...,45542,70927,9/9/16,09:24:53 8 Nov 2016
4369,2016,President,now-cast,Clinton vs. Trump vs. Johnson,11/8/16,Alabama,11/1/2016,11/7/2016,SurveyMonkey,C-,...,34.52791,54.35276,3.682124,NaN,NaN,https://www.surveymonkey.com/elections/map?pol...,48860,76550,11/8/16,09:24:53 8 Nov 2016
5504,2016,President,now-cast,Clinton vs. Trump vs. Johnson,11/8/16,Alabama,7/19/2016,7/19/2016,Strategy Research,NaN,...,34.09074,57.64280,NaN,NaN,NaN,http://wkrg.com/2016/07/21/trump-wins-alabama-...,44747,68431,8/2/16,09:24:53 8 Nov 2016